### ISSUE TITLE
24.05 ZHF Hackathon Feedback

### ISSUE THREAD

**Issue by ners** [nix-community/ZurichZHF#5]
Dear Nixers!

Thank you for participating in the hackathon that we ran on 2024-05-25 and 2024-05-26. We sincerely appreciate your presence and active involvement in making it a successful event. We would like to hear your feedback and insights to help us improve future events. Your input is invaluable to us!

We kindly request you to take a few minutes to provide your feedback. Here are some example questions to consider; **you don't have to answer all of them**.

1. Organisation:
  - How would you rate the overall organisation of the event?
  - Did you find the registration process smooth and hassle-free?
  - Were the communication channels (Meetup, Matrix room) effective?

2. Atmosphere and networking:
  - Did you find the event environment conducive to learning and networking?
  - Were there enough opportunities to interact with other attendees and exchange ideas?
  - Did you feel comfortable asking questions and participating in discussions?

3. Logistics:
  - Were the venue and facilities suitable?
  - Did you encounter any issues with seating, electrical equipment, or other logistics?
  - How would you rate the overall timing and duration of the event?

4. Suggestions for improvement:
  - Do you have any suggestions or ideas for improving future events?
  - Are there any specific topics or formats you would like to see in future events?
  - Is there anything else you would like to share that would help us enhance the experience?

**Comment by Nebucatnetzer** [comment]
I really enjoyed the event and the food was amazing!

One improvement over last time was that we stayed in Rappi for dinner.
Thus avoiding the overhead of changing location and it was another great opportunity to get to know each other.
Maybe we could keep that up?

To make it easier for the organisation we could ask participants to confirm in advance if they stay for dinner?
Next time will be during winter time so it will be harder to get space that fits all participants.
Or we stay at the school and rearrange the tables in one of the rooms?
